### ISSUE TITLE
Error 32

### ISSUE THREAD

**Issue by O-D-S** [msztolcman/subst#2]
Python 2.7
Windows 7

Error message:
`ERROR: Error replacing "C:\Batch\Test.txt" with "c:\users\xy\appdata\local\temp\tmpifvfgn": [Error 32] The process cannot access the file because it is being used by another process`

The file does not seem to have been closed by the script.

**Comment by msztolcman** [comment]
Hi O-D-S, thanks for your report!

I have limited access to Windows machine, but I will try to verify how it works on Windows in few days.

**Comment by O-D-S** [comment]
Hi msztolcman,

Although I know almost nothing about Python, I was able to make your script run with two little modifications. But I don't want to call it a bug fix, because I neither know, if my modifications have any negative side effects, nor I have tested subst.py with all options.

1. Before the temporary file can be renamed (which is synonymous with "moved"), it has to be closed. The open temp file seems to be the reason for the error 32 on Windows.
2. But even if it is closed, it cannot be moved with "os.rename(tmp_path, src_path)" on Windows. This results in another error. So I tried to move it with "shutil.move(tmp_path, src_path)" instead. And this works.

I have replaced the following line in your code
`        os.rename(tmp_path, src_path)`

with these two lines

```
        tmp_fh.close()
        shutil.move(tmp_path, src_path)
```

I am not sure, if this is elegant code, because in the end the function (?) "def _process_file__regular(src_path, cfg, replace_func)" is still the original "try", in which the temp file is closed:

```
    try:
        tmp_fh.close()
    # pylint: disable=bare-except
    except:
        pass
```

And please have a look at this thread:

https://stackoverflow.com/questions/8858008/how-to-move-a-file-in-python

**Comment by msztolcman** [comment]
Hi O-D-S,

Thanks for great research! It explains a lot. Especially if I had no possibility to do any tests on Windows.
I've fixed it in similar way as you proposed (using `shutil.move`), but closing file handle is just moved upper above `shutil.move` call.

> By the way: I have noticed, that the replacements with subst.py are slow in comparison with ssr.exe (written by Ross MacGregor). Probably because of Python.

Maybe it's because of Python, but also I've never look at speed of this tool. But of course it's a good idea to work on it. I've created an issue #6 for this.

**Comment by O-D-S** [comment]
I only wonder, why it works with shutil.move, but not with os.rename on Windows, because [the Python doc says in relation to shutil.move:](https://docs.python.org/2/library/shutil.html#shutil.move)

> If the destination is an existing directory, then src is moved inside that directory. If the destination already exists but is not a directory, it may be overwritten depending on os.rename() semantics.

But with regard to the os.rename semantics [the Python doc says:](https://docs.python.org/2/library/os.html#os.rename)

>  On Windows, if dst already exists, OSError will be raised even if it is a file;

But with shutil.move no OSError is raised. It overwrites the source file as intended. There is no need to remove the source file first, before the temporary file can take its place.

Maybe I don't understand the meaning of the word _semantics_ in this case.

**Comment by msztolcman** [comment]
I think it's related rather to part:

> If the destination is on the current filesystem, then `os.rename()` is used. Otherwise, src is copied to dst using `copy_function` and then removed.

`os.rename` works great on same filesystem, but can cause problems on different filesystems.
Since Python 3.3 there is also `os.replace` that should work better, but `subst` works also with Python 2.7, so `shutil.move` is better solution here.

**Comment by msztolcman** [comment]
This issue is already fixed in master branch, but not fully tested yet. It would be great if you can test it on Windows, if all your usages will work as expected, then I will release new version of `subst` with all these fixes. Thanks!

**Comment by O-D-S** [comment]
No error 32 anymore.

**Comment by msztolcman** [comment]
Great! Thank you :)
