### ISSUE TITLE
-t/--string param shouldn't require any argument

### ISSUE THREAD

**Issue by O-D-S** [msztolcman/subst#4]
`python.exe subst_py -b --encoding-file utf8 --count 1 --verbose --stdout -t -p "END PKCS7" -r "bread" "Testfile.ttx"`

results in usage info and:
`subst.py: error: argument -t/--string: expected one argument`

Which kind of argument does the -t option expect?

I ask, because I am getting this output, if I omit the "-p":

```
subst.py: error: must be provided --pattern and --replace options, or --pattern-
and-replace.
```
-------------------------------

If I have more questions of this kind, can I ask them in this thread?

**Comment by msztolcman** [comment]
Hi O-D-S,

It's just a bug, -t is just and only a switch, and shouldn't require any param.

> If I have more questions of this kind, can I ask them in this thread?

It's better to open different issues for this kind of problems, because later it's easier to searching for issues, and I can manage issues directly from commits.

Thanks for your report! I have fixed it, I think today or tomorrow I should release new version with this fix included.

**Comment by msztolcman** [comment]
This issue is already fixed in master branch, but not fully tested yet. It would be great if you can test it on Windows, if all your usages will work as expected, then I will release new version of `subst` with all these fixes. Thanks!

**Comment by O-D-S** [comment]
No error with the -t option anymore. With regard to the speed I don't recognize a difference with or without the option.

**Comment by msztolcman** [comment]
Great!

> With regard to the speed I don't recognize a difference with or without the option.

Yeah, there shouldn't be any difference. In fact replacement is done using regular expressions, but all characters significant for regexps are escaped... ;) Just little trick :)

Thanks for your time :)

**Comment by O-D-S** [comment]
> Thanks for your time :)

Mmh. I was searching a long time for such a Python script. Thanks for _your_ time, efforts, the license of the script, the fact, that it is open source, and so on!
