### ISSUE TITLE
subst.py changes line ending from Windows to Unix

### ISSUE THREAD

**Issue by O-D-S** [msztolcman/subst#5]
Edited: subst.py changes line endings / newline characters from Windows to Unix.

**Comment by msztolcman** [comment]
Hi O-D-S,

What do you mean by 'DOS utf8'/'Unix utf8'? You mean only what you pointed after '/' char, it means only new line characters? Or something more? The only thing I can think for this sentence is something related to [BOM](https://en.wikipedia.org/wiki/Byte_order_mark), but I've tested it and it doesn't change BOM.

I've fixed issue with new line, but please tell me a little more about different versions of UTF-8 :)

BTW, I'm very glad of your bug reports, thank you for every issue you've created :)

**Comment by O-D-S** [comment]
As far as I can see, subst.py changes only the newline characters from Windows to Unix. Subst.py (fortunately) neither adds nor deletes a BOM. I have checked that in UltraEdit Hex modus just now. So the problem is not related to the encoding, but only to the newline characters.

I will change the title of this issue.

**Comment by msztolcman** [comment]
OK, so I will push changes today. Thanks :)

**Comment by msztolcman** [comment]
Hi O-D-S,

Problem is indeed in place where temp file is created, but a moment later, where this temp file is opened. In Python 3 there was some change to `open` function, and by default text files are opened in [universal-newlines](https://docs.python.org/3/glossary.html#term-universal-newlines) mode, and this cause problems. In Python 2 is no feature like this. So the solution I have is to wrap function that is opening file and handle it properly. 

I never realized this problem, because I am working in unix-only environments, and there \n new line character is by default. As I wrote previously, new-lines bug is already fixed, I just wanted to wait to informations about UTF-8 dos/unix before publishing it :) Thank you for your involvement in resolving this!

**Comment by msztolcman** [comment]
This issue is already fixed in master branch, but not fully tested yet. It would be great if you can test it on Windows, if all your usages will work as expected, then I will release new version of `subst` with all these fixes. Thanks!

**Comment by O-D-S** [comment]
I have tested it just now, but subst.py still changes the line endings from Windows to Unix.

**Comment by msztolcman** [comment]
Hm, it works good on unix, my \r\n file has still \r\n eol characters after replacements. To be clear: I don't released new version yet, I just pushed changes to repository. How do you install `subst`? Are you using `pip`, or maybe just downloaded `subst.py`, or in other way? Are you sure you are now using [latest version](https://raw.githubusercontent.com/msztolcman/subst/master/subst.py)?

**Comment by O-D-S** [comment]
I have downloaded subst.py. I don't install subst.py to the Python directory. Subst.py is in my batch folder. When I command subst.py, I specify the path tho python.exe followed by the path to subst.py in my batch folder.

I know, that the most recent version was used, because I already have checked, if the exit code works. (By the way: the exit code works.)

**Comment by msztolcman** [comment]
OK, thanks, I will look on it more :(

**Comment by msztolcman** [comment]
Could you also give me info about your python version (`python --version`) and what terminal you are using? It's `cmd` or powershell, or maybe something other?

**Comment by O-D-S** [comment]
Python 2.7.11
And the terminal is cmd.

**Comment by msztolcman** [comment]
Hm, veeery strange.
First, this issue with universal-newlines is only in Python3.
Second, I've tested this on Windows few minutes ago, and in both: Py2.7 and Py3.6 it works well - there is no changes to new line characters. I will investigate it more later.

**Comment by O-D-S** [comment]
> Second, I've tested this on Windows few minutes ago, and in both: Py2.7 and Py3.6 it works well - there is no changes to new line characters. 

This is very odd.

But I have checked it again. I have replaced Test with Best. Hex 0D is CR, Hex 0A is LF.

00000000h: 54 65 73 74 **0D 0A** 54 65 73 74                   ; Test..Test

00000000h: 42 65 73 74 **0A** 42 65 73 74                      ; Best.Best

**Comment by msztolcman** [comment]
Yeah, I've tested also using hex-dump, and there was `\0D\0A` after processing. I don't know yet why, needs more investigation.

**Comment by O-D-S** [comment]
With regard to the version of subst.py, in which I only had fixed the error 32:

I have tried to import io and

replace

`    with open(src_path, 'r') as fh_src:`

with

`    with io.open(src_path, 'r', newline='') as fh_src:`

And now it works. Tested with Python 2.7.11, on Windows 7. I don't know, if this works on UNIX platforms or with a different Python version.

Please always keep in mind, that I am not a programmer. I just have googled for newline in context with Python. In other words: With regard to the code I don't know exactly, what I do. I just have tried io.
--------------------------------------------

In your actual version you are import ing functools and there is the following line in your code:

`file_opener = functools.partial(open, newline='') if not IS_PY2 else open`

If I understand this line correctly, functools.partial is only used for the opening of src_path, if not Python 2.x is used. But because I am using Python 2.7. So the newline keyword cannot work here. And if I simply delete the string " if not IS_PY2 else open", I get an error.

**Comment by msztolcman** [comment]
Hi @O-D-S, please look for new version of `subst`. I've rewritted many parts related to encodings - this fixed problems with new line characters, but casued some problems with processing data from stdin... but on the and it works now. Not all problems with this are solved yet, but I will work on it in next few days. But I would be glad if you can test current behavior on Windows :)

**Comment by msztolcman** [comment]
And also answering to your research: you've found interesting thing about `io.open` - I mean it handle 'newline' param. I missed it :)

Anyway, you've done great job with your research, and it also would fix problems with new lines characters, but I started other way first, and later i've spent a lot of time resolving encoding issues. This was a real challange (remembering that handling encodings in Python2 and Python3 is done in veeeery different ways).

About backward compatibility: it was 2.6, but this version should be compatible with Python 2.7 and 3.3+. (I've added this info to README, thanks for pointing this :) )

**Comment by O-D-S** [comment]
I have made a few tests and your solution seems to work now.

Wildcards in file names also work now. There is only an issue with wildcards in the names of directories: https://github.com/msztolcman/subst/issues/7#issuecomment-330663997

Except from that I think, you have fixed all bugs, that I have recognized until now. That's really great. Thanks again for this script! I will use it, although it is slower than my solution with the Windows command line tools rxrepl.exe or ssr.exe. The platform compatibility and the open source are more important for me.

It may be, that I have a few proposals with regard to improvements of the documentation of subst.py. For example a link to a source, in which PCRE is explained. I have found this for example yesterday: "https://www.debuggex.com/cheatsheet/regex/pcre". At the bottom of the page is a link to a regex tester.

But your documentation already is relative good in comparison to other projects, that I have seen.

**Comment by msztolcman** [comment]
> I will use it

Great! Thanks :)

> It may be, that I have a few proposals with regard to improvements of the documentation

Please, do not hesitate to make issues also for documentation, I know this is something that can be always better :)

> For example a link to a source, in which PCRE is explained

In included help there is few links to [docs.python.org site](https://docs.python.org/3/library/re.html), do you think it's not enough explained there?

**Comment by O-D-S** [comment]
No, that's good. I only had searched for PCRE yesterday and found the regex tester on debuggex.com. You have written, that PCRE is a much more widely used dialect and I did not know the meaning of the abbreviation – that it means "Perl compatible".

**Comment by msztolcman** [comment]
You're right, it's too obvious for me, and I didn't see it's not clear for everyone. I extended some informations in README, and added some resources about reular expressions (also these you gave to me few comments above).
