### ISSUE TITLE
expand wildcards in paths (especially for windows)

### ISSUE THREAD

**Issue by O-D-S** [msztolcman/subst#7]
```
    with file_opener(src_path, 'r') as fh_src:
        cnt = replace_func(fh_src, dst_fh, cfg.pattern, cfg.replace, cfg.count)
        if cfg.verbose or cfg.debug:
            debug('%s replacements' % cnt, indent=1)
```

and

```
    if args.verbose:
        debug('There was %d changes in %d files.' % (cnt_changes, cnt_changed_files))
```

results in:

```
Path to file
    "number" replacements
There was "number" changes in "number" files.
```

"There was "number" changes in "number" files." – Doesn't subst.py expects exactly one file? I neither can specify a directory, nor jokers for file names and extensions. So the number of files can be only 0 or 1. But because the users knows, that he has specified one file only, the info about the number of files is useless in my opinion. And because there already was a message about the number of replacements, the whole line "There was "number" changes in "number" files." is useless.

Specifying a directory instead of a file would result in the following error message:

```
C:\alpha\beta\"
    ERROR: Path "C:\alpha\beta\"" doesn't exists

By the way, please notice the two ", that follow beta\. 
```

**Comment by msztolcman** [comment]
Hi O-D-S,

`subst` can handle many paths, but it you must specify these paths to `subst`. And you're right, directories cannot be specified :)
But if you specify more then one file, you can have result similar to:

    % py3 subst.py --verbose -p a -r A dos.txt second.txt
    /Users/mysz/Projects/subst/dos.txt
        3 replacements
    /Users/mysz/Projects/subst/second.txt
        3 replacements
    There was 6 changes in 2 files.

But this is interesting. In unix, it's shell job to expand 'jokers', tool always receives exact paths. Ie.:

    ls -l dos*

Can result in something like:

    dos.txt      dos.txt.bak

but `ls` tools receives params: `dos.txt`, `dos.txt.bak`. Same with `subst`: I can call it like:

    subst -s 's/a/A/g' *.txt

and it works on all files with `.txt` extension.

If I understand correctly, on windows it doesn't work?
I can do a workaround for this, but I need to do some tests in windows machine, to be sure how it exactly works. And maybe there are some differencies between `powershell` and `cmd` ;)

**Comment by O-D-S** [comment]
With regard to the jokers in file names:

> I can do a workaround for this

For my own purposes a workaround actually would not be an improvement, because the subst.py command is in a for loop in my batch scripts. Example:

```
@echo off
call Myvars
for %%f in (DecompileD\*.*) do (
%subst_py_Com% -b --encoding-file utf8 --count 0 --verbose -p "string" -r "\g<0>" "%%f"
)
```

%subst_py_Com% is a variable, the path to Python exe followed by the path to subst.py
And Myvars is another batch script, in which all the pathes to Python scripts are set.

Generally I would say, that a workaround could be useful. I would say: Do it, if it isn't another potential source of error. 

> subst.py --verbose -p a -r A dos.txt second.txt

That's good to know. In this case the info about the number of files naturally makes sense. And the two infos about the number of changes/replacements also make sense. I just have checked, what happens, if I specify more than one file. 

I only would slightly correct the message with regard to the grammar and the wording:

The message, that you get for each file is "number" replacements. I think, it would be consequent, to keep the message for the whole command / all files also simple:

"number" replacements in "number" files

So, if you specify two files, the output in the command line windows would be:

Path to file
    "number" replacements
Path to another file
    "number" replacements
"number" replacements in "number" files

**Comment by msztolcman** [comment]
It's better to call `subst` once with multiple files then once for every file - it may be related to slowness you mentioned in another issue :) It means that for every file you are paying a cost of running interpreter (Python), then compiling `subst`, and then executing replacements. If you have 100 files, you are paying it 100x :)
I think calling it in your way has sense only when every file has different pattern or replacement.

Also, in command:

    %subst_py_Com% -b --encoding-file utf8 --count 0 --verbose -p "string" -r "\g<0>" "%%f"

`--count 0` is not required - 0 is default value if you are using `-p` and `-r` switches (there is slightly different behavior when you are using `-s` switch, but it's another case).

About message: I am working on changing messages in verbose mode a little more, so currently I will not change this, but I'll back to this soon.
But still, I appreciate your feedback, thanks!

**Comment by msztolcman** [comment]
@O-D-S I've added `--expand-wildcards` switch, it should be helpful for you in this situation :)

**Comment by O-D-S** [comment]
> I've added --expand-wildcards switch, it should be helpful for you in this situation :)

Actually the switch has only the effect, that I don't get an error message, when I specify `My_directory\*.*` for example. But nothing will replaced in the files, that are contained in My_directory.

In fact I even don't get an error "Path does not exist" anymore, if I specify a file name _without_ a wildcard to a file, that does not exist.

**Comment by O-D-S** [comment]
"C:\myDir1\myDir2\*.txt" works now. Great!

"C:\myDir1\myDir2\*\myFile.txt" results in an error. (I don't need a fix for that, but I want to inform you.)

WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'C:\\myDir1\\myDir2\\*\\*.*'

**Comment by msztolcman** [comment]
@O-D-S I've changed again expanding wildcards (I've found much better solution). Could you test both cases again on Windows?

**Comment by O-D-S** [comment]
I have tested all three cases. With the -W option none of these examples work:

C:\MyDir1\*\*.*
C:\MyDir1\MyDir2\*.*
C:\MyDir1\MyDir2\MyFile.txt

**Comment by msztolcman** [comment]
OK, another try... i've made some exclusions especially for windows, and tested this one on virtual machine. I hope it will works now ;) Could you test it again?

**Comment by O-D-S** [comment]
It still does not work. Exactly the same results for all three cases. 0 replacements in 0 files. But also no errors.

**Comment by O-D-S** [comment]
[I have asked for help on the German Python forum.](https://www.python-forum.de/viewtopic.php?f=1&t=41272&p=315365#p315365)

Do you speak German? If not, [the script, that the user "snafu" has posted, ](https://pastebin.com/5tvZJr0e)may help to fix the wildcard bug.

**Comment by msztolcman** [comment]
Hi O-D-S,

Thanks for your help :) I don't speak German, but given script just uses same module as I am using, it means `glob`. 

If we can talk about particular parts:

    path = os.path.expanduser(os.path.expandvars(path))

It just resolves env variables in path. I added this too, it can be useful.

    if os.altsep is not None:
        path = path.replace(os.altsep, os.sep)

It should be handled by `os.path.normcase`, added.

    if not glob.has_magic(path) or path.endswith(os.sep):
        path = os.path.join(path, '*')

I don't like this kind of "magic", when you pass path to file it works in different way, if you pass path to directory it works in another... if you want add all files from given directory, just use 'c:\path\*' :)

And later is:

    filenames = (fn.rstrip(os.sep) for fn in glob.iglob(path))

it is the same what is used in current version in `subst`. I've also added normalization of paths etc. 

The key is: why it doesn't work on your computer. It just works on my virtual machine, and more: it's working on physical machine I have access too. Currently no ideas... I cannot reproduce it :(

**Comment by O-D-S** [comment]
> The key is: why it doesn't work on your computer.

The actual version partially works:
MyDir1 contains MyDir2. MyDir 2 contains Text.txt

`%subst_py_Com% -b -W --encoding-filesystem utf8 --verbose -p "Test" -r "Match" "MyDir1\*\*"`

->

```
c:\fdk_06.07.2017_batch\[de]comp\mydir1\mydir2\test.txt
    8 replacements
There was 8 replacements in 1 file.
```

But if MyDir2 contains a directory MyDir3 along with Text.txt:

```
c:\fdk_06.07.2017_batch\[de]comp\mydir1\mydir2\mydir3
    ERROR: Path "c:\fdk_06.07.2017_batch\[de]comp\mydir1\mydir2\mydir3" is not a
 regular file
```

If you have a folder, in which a folder and a file without extension is stored, you will get an error message. And *.* also matches directories, that have a dot in their names.

Except from that the path in the error message is lowercase.

And i have noticed, that you try to build the plural now:

1 replacement
2 replacements
There was 1 replacement in 1 file
There **was** 2 replacements in 1 files

**Comment by msztolcman** [comment]
It looks like it work as expected :) I don't want to expand directories. Also don't support recursive expanding. So star will expand you everything in current directory (and not in subdirectories).

> Except from that the path in the error message is lowercase. (Probably this is meant by normalization.)

Yep, it's an effect of normalization :)

> There is only a little mistake with regard to was and were.

You're right... I need to change this message. Thanks for pointing this out :) But I will back to this in near future, I am going to release version 1.0, and there these messages will change at all.

**Comment by O-D-S** [comment]
> It looks like it work as expected

Yes. In the thread on the German Python forum, a user writes, that the integration of os.path.isdir(filename) (with adjusted behavior) could maybe help. But my plan wasn't to be a mediator between you and the forum users. It was an invitation to Python programmers with access to a Windows computer, that are interested in your script, to engage here, nothing less, nothing more.

**Comment by msztolcman** [comment]
I understand, thanks :) But my knowledge of German is something like 'Ich heisse Marcin Sztolcman, Ich wohne from Poland' etc, I had few lessons of this language about 20y ago :D
